### ISSUE TITLE
Djanjo Help Tutorial Produces Import Error When Follow Exactly

### ISSUE THREAD

**Issue by skamensky** [pythonanywhere/help_pages#11]
The Django Tutorial brings you to an error when followed exactly. I've tried this with both python 2.7 and 3.5.
[DjangoTutorial](https://github.com/pythonanywhere/help_pages/blob/master/articles/DjangoTutorial.md
)
The point that I'm stuck at is

`python ./manage.py syncdb
`

Error that's given is:

```
23:52 ~/mysite $ python ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named myapp.apps
```

Here's some more from the error log
[full error log.txt](https://github.com/pythonanywhere/help_pages/files/746488/full.error.log.txt)

**Comment by conradho** [comment]
Hi there,

Thanks for letting us know! We have updated the [django tutorial](https://github.com/pythonanywhere/help_pages/blob/master/articles/FollowingTheDjangoTutorial.md).

If you are having any further problems, please post on the [PythonAnywhere forums](https://www.pythonanywhere.com/forums/) and or send feedback/an email to the PythonAnywhere staff!
