### ISSUE TITLE
Cannot create a virtualenv

### ISSUE THREAD

**Issue by OmkarPathak** [pythonanywhere/help_pages#28]
Whenever I try to create a virtual environment using `mkvirtualenv` or `virtualenv` commands, the setup gets stuck and no further progress happens. Hitting `ctrl_c` gives the result as:

10:12 ~ $ virtualenv -p python3 arham
Running virtualenv with interpreter /home/anujdhongade/.local/bin/python3
Using base prefix '/usr'
New python executable in /home/anujdhongade/arham/bin/python3
Also creating executable in /home/anujdhongade/arham/bin/python
Installing setuptools, pip, wheel...^Cdone.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2328, in <module>
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 671, in main
    raise SystemExit(popen.wait())
  File "/usr/lib/python2.7/subprocess.py", line 1376, in wait
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 901, in install_wheel
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 769, in call_subprocess
    line = stdout.readline()
KeyboardInterrupt

Please help!

**Comment by conradho** [comment]
that traceback sounds like you just exited the process in the middle while it was still installing?

Please contact us about support questions on the forums or by the send feedback button from your PythonAnywhere account
